### ISSUE TITLE
Look into android latest (7.1) failure

### ISSUE THREAD

**Issue by vweevers** [airtap/browsers#3] opened 2018-02-13 22:51 UTC

**Comment by jhiesey** [comment] 2018-02-22 08:26
Haven't looked too deep, but my guess is this is related to the following caveat:
"Android 7.0 only comes on the GoogleAPI flavor, so make sure that you have your desired capability set to `deviceName`: `Android GoogleAPI Emulator`." seen [in the release notes](https://wiki.saucelabs.com/display/DOCS/2017/03/31/Android+6.0+and+7.0+Support+Released)

**Comment by jhiesey** [comment] 2018-02-27 03:10
OK, so it works if we set `deviceName: Android GoogleAPI Emulator`, but that specific string is never returned from the sauce labs rest api (https://saucelabs.com/rest/v1/info/browsers/webdriver) as a `long_name` value.

On the other hand, more specific names like 'Samsung Galaxy S8 GoogleAPI Emulator' are returned. We could choose one of the available names arbitrarily, or hardcode 'Android GoogleAPI Emulator' somewhere (not ideal). Thoughts?

**Comment by ralphtheninja** [comment] 2018-02-27 03:14
In which way is this broken?

**Comment by jhiesey** [comment] 2018-02-27 03:17
Any test that uses android 7 fails:

```
/Users/jhiesey/Projects/node/airtap/node_modules/wd/lib/webdriver.js:134
        err = new Error('The environment you requested was unavailable.' + jsonData.value ? ('\n' + jsonData.value.message) : '');
                                                                                    ^

TypeError: Cannot read property 'value' of undefined
    at /Users/jhiesey/Projects/node/airtap/node_modules/wd/lib/webdriver.js:134:85
    at Request._callback (/Users/jhiesey/Projects/node/airtap/node_modules/wd/lib/http-utils.js:88:7)
    at Request.self.callback (/Users/jhiesey/Projects/node/airtap/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/Users/jhiesey/Projects/node/airtap/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/Users/jhiesey/Projects/node/airtap/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
```

The exception thrown in webdriver itself when trying to generate the error message is a separate issue.

**Comment by ralphtheninja** [comment] 2018-02-27 04:29
Some digging (and annoying multiple property translations) just to get some more information on what it looks like now.

When asking the sauce labs api we get the following meta data:

```json
{
  "short_version": "7.1",
  "long_name": "Samsung Galaxy Tab A 10 GoogleAPI Emulator",
  "api_name": "android",
  "long_version": "7.1.",
  "device": "GalaxyTabA10GoogleAPI",
  "latest_stable_version": "",
  "automation_backend": "webdriver",
  "os": "Linux"
}
```

Current functionality is to pick `.api_name`, which gets translated to `.name` here:

https://github.com/airtap/airtap/blob/d0dd74a8326602d0bdc4d40f9d3f23baee824f49/lib/get-saucelabs-browsers.js#L42-L56

Which then gets translated to `.browser` here:

https://github.com/airtap/airtap/blob/master/lib/airtap.js#L55

Which then gets translated to `.browserName` here:

https://github.com/airtap/airtap/blob/master/lib/sauce-browser.js#L59

**Comment by ralphtheninja** [comment] 2018-02-27 04:30
I'm thinking the _ideal_ solution is to be able to use the first info struct we get from their api and just pass that back to sauce labs when requesting a test and get rid of all these translations in the first place. But that would require interaction with sauce labs and get their support to improve on this.

**Comment by ralphtheninja** [comment] 2018-02-27 10:25
Some more information. When using `wd.init(initOpts)` we pass in a [DesiredCapabilities](https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities) which has `browserName`, `version` and `platform`, which doesn't give us much to go on. If we can't do `browserName='android'` and `version='7.0'` it seems to me we're out of luck.

Please correct me if I'm wrong.

Also, the status on the `JsonWireProtocol` for Selenium is `OBSOLETE`. Not sure what that exactly _means_ but I'm guessing sort of oldish and soon-to-be-deprecated-or-killed? Maybe want to take a look into the `W3C` specification. All we're doing anyway is _picking_ a browser and telling it to load a page and no fancy DOM stuff, so seems to me it should be fairly easy to switch to something more up to date.

**Comment by ralphtheninja** [comment] 2018-02-27 10:26
> Some more information. When using wd.init(initOpts) we pass in a DesiredCapabilities which has browserName, version and platform, which doesn't give us much to go on. If we can't do browserName='android' and version='7.0' it seems to me we're out of luck.

If we can't get that ^ to work it seems to me that the problem lies at Sauce Labs.

**Comment by ralphtheninja** [comment] 2018-02-27 10:45
Oh apparently `JsonWireProtocol` is the way to go. I think obsolete above just means that the api docs are old. Not really any use of switching from `wd` to [webdriverio](https://github.com/webdriverio/webdriverio) then

**Comment by ralphtheninja** [comment] 2018-03-08 12:55
https://github.com/admc/wd/pull/522 was submitted to fix the `jsonData` error.

**Comment by feross** [comment] 2018-05-25 06:26
I just noticed the `jsonData` error starting to happen with iPhone latest as well :-(

```yml
browsers:
  - name: iphone
    version: latest
```

**Comment by feross** [comment] 2018-05-25 06:39
If I manually update `wd` to greater than 1.6.1 to fix the `jsonData` bug, then I get this error which is still preventing iPhone 11.3 tests from running:

```
airtap browser error (iphone@11.3: [init({"name":"arch","browserName":"iphone","version":"11.3","platform":"Mac 10.13"})] The environment you requested was unavailable.: Appium 1.8.0 does not support Mac 10.13. Please check our platform configurator (https://saucelabs.com/docs/platforms)), restarting +165ms
```

What does this mean?

> Appium 1.8.0 does not support Mac 10.13. Please check our platform configurator (https://saucelabs.com/docs/platforms)

Any ideas?

**Comment by vweevers** [comment] 2018-05-25 06:46
I had issues with the same browser yesterday: https://github.com/airtap/airtap/issues/152#issuecomment-391771098. But after a few retries it did succeed.

**Comment by feross** [comment] 2018-05-25 07:03
I just merged https://github.com/airtap/airtap/pull/165 which upgrades `wd` so at least the `jsonData` bug is fixed on `master`.

This still doesn't fix Android 7. Still getting:

```
airtap browser error (android@7.1: [init({"name":"arch","browserName":"android","version":"7.1","platform":"Linux"})] The environment you requested was unavailable.: Unsupported OS/browser/version/device combo: OS: 'unspecified', Browser: 'android', Version: '7.1.', Device: 'Android Emulator'), restarting +186ms
```

**Comment by feross** [comment] 2018-05-25 07:03
@vweevers Retrying does not help for the iPhone error I'm getting. It seems similar to the Android 7 issue (i.e. it's a browser configuration issue):

> Appium 1.8.0 does not support Mac 10.13. Please check our platform configurator (https://saucelabs.com/docs/platforms)

**Comment by vweevers** [comment] 2018-05-25 09:06
Seeing the same thing now on memdown. To verify that appium is the problem, maybe we can try `SAUCE_APPIUM_VERSION=X airtap test.js`? Where `X` is an older version (I don't know which version though).

See https://github.com/airtap/airtap/blob/67246f20b52fcf465331b0adfbde18edc06bde0e/lib/sauce-browser.js#L59-L61

**Comment by vweevers** [comment] 2018-05-25 09:20
Tried `SAUCE_APPIUM_VERSION=1.7.2`. Same error:

```
[init({"build":"432","name":"memdown","browserName":"iphone","version":"11.3","platform":"Mac 
10.13","appium-version":"1.7.2","tunnel-identifier":"432.1"})] The environment you requested was 
unavailable.: Appium 1.7.2 does not support Mac 10.13. Please check our platform configurator 
(https://saucelabs.com/docs/platforms)
```

**Comment by vweevers** [comment] 2018-05-25 10:01
Another potential problem is that `sauce-browsers` / `airtap` only dedups browsers by OS, not device. The Sauce Labs API returns multiple iphones with the same version and os:

```json
 {
  "short_version": "11.3",
  "long_name": "iPhone 5s Simulator",
  "api_name": "iphone",
  "long_version": "11.3.",
  "device": "iPhone 5s",
  "latest_stable_version": "",
  "automation_backend": "webdriver",
  "os": "Mac 10.13"
}, {
  "short_version": "11.3",
  "long_name": "iPhone X Simulator",
  "api_name": "iphone",
  "long_version": "11.3.",
  "device": "iPhone X",
  "latest_stable_version": "",
  "automation_backend": "webdriver",
  "os": "Mac 10.13"
}
```

This can cause `airtap` to queue the same browser more than once:

```
airtap:sauce:iphone:11.3 browser conf: {"name":"memdown","build":"432","browser":"iphone","version":"11.3","platform":"Mac 10.13"}
airtap:sauce:iphone:11.3 browser conf: {"name":"memdown","build":"432","browser":"iphone","version":"11.3","platform":"Mac 10.13"}
```

**Comment by ralphtheninja** [comment] 2018-05-25 10:12
> Another potential problem is that sauce-browsers / airtap only dedups browsers by OS, not device.

@vweevers Lets dedup this in `airtap`.

**Comment by ralphtheninja** [comment] 2018-05-25 10:15
Also, I think we should do something about the translations I mentioned [above](https://github.com/airtap/browsers/issues/3#issuecomment-368743736).

**Comment by vweevers** [comment] 2018-05-25 10:15
> Also, I think we should do something about the translations I mentioned above.

Long-term, definitely. But for lack of unit tests, we should be careful to change too much at once.

**Comment by vweevers** [comment] 2018-05-25 10:16
@feross in the mean time you can downgrade to iphone 11.2:

```yaml
  - name: iphone
    version: 11.2
    platform: Mac 10.12
```

**Comment by vweevers** [comment] 2018-05-25 10:20
(beware though, because of the dedup issue, this will start 12 identical jobs!)

**Comment by vweevers** [comment] 2018-05-25 12:20
> in the mean time you can downgrade to iphone 11.2

Scratch that. iphone 11.2 and ipad are now also failing.

**Comment by lpinca** [comment] 2018-05-27 06:13
> Another potential problem is that sauce-browsers / airtap only dedups browsers by OS, not device. 

I think this is by design, if you don't specify `platform`, browsers with the same version are deduplicated. On the other hand if you specify `platform` you want **all** browsers for that platform to be tested. For example

```yaml
- name: iphone
    version: 11.2
    platform: Mac 10.12
```

asks to test all browsers whose name matches iphone, have version 11.2 and platform Mac 10.12, not just one.

**Comment by vweevers** [comment] 2018-05-27 06:28
@lpinca you're not wrong. For the time being though, we have to deduplicate (in airtap) because airtap currently ignores the `device` property. So the input browsers are distinct but when we send it to Sauce Labs they're all the same.

**Comment by ralphtheninja** [comment] 2018-06-03 23:28
@vweevers It's basically _this_ key that should be unique, right?

https://github.com/airtap/airtap/blob/c760dac878943dbf66745097edf254ac67eda49c/bin/airtap.js#L150-L151

Damnit! Sometimes I can't get permalinks to work.

**Comment by ralphtheninja** [comment] 2018-06-03 23:32
No, nevermind.

**Comment by ralphtheninja** [comment] 2018-06-03 23:38
Well, actually, yes :laughing:

These property translations are painful to me. In other words we should dedupe on `.os` and `.api_name` properties in the _original_ data we get from `sauce-browsers`.

They translate into:

* `.os` -> `.platform`
* `.api_name` -> `.browser`

But isn't the the final `.version` property important as well? So maybe it's the data to `zuul.browser()` that should be unique:

https://github.com/airtap/airtap/blob/c760dac878943dbf66745097edf254ac67eda49c/bin/airtap.js#L153-L157

**Comment by vweevers** [comment] 2018-06-04 07:56
> Sometimes I can't get permalinks to work.

Those don't work cross-repo, sadly.

Let's continue discussion at https://github.com/airtap/airtap/issues/168?

**Comment by ralphtheninja** [comment] 2018-06-04 08:06
> Those don't work cross-repo, sadly.

Makes sense now!

**Comment by jhiesey** [comment] 2018-09-24 21:37
I'm still getting something similar:

```
Error: android@7.0: [init({"build":"280","name":"[secure]","browserName":"android","version":"7.0","platform":"Linux","tunnel-identifier":"280.1"})] The environment you requested was unavailable.: Misconfigured -- Unsupported OS/browser/version/device combo: OS: 'unspecified', Browser: 'android', Version: '7.0.', Device: 'Android Emulator'
    at /home/travis/build/jhiesey/[secure]/node_modules/wd/lib/webdriver.js:140:15
    at Request._callback (/home/travis/build/jhiesey/[secure]/node_modules/wd/lib/http-utils.js:89:7)
    at Request.self.callback (/home/travis/build/jhiesey/[secure]/node_modules/request/request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/travis/build/jhiesey/[secure]/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/travis/build/jhiesey/[secure]/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
```

Is this the same issue?

**Comment by vweevers** [comment] 2018-09-24 21:47
@jhiesey if you're on latest `airtap`, then yes. It seems we haven't gotten to the root cause yet. We've updated `wd` (https://github.com/airtap/airtap/pull/165) and fixed duplicates (https://github.com/airtap/airtap/pull/181), but android 7 is something else

**Comment by jhiesey** [comment] 2018-09-24 21:49
Yup I'm using v0.1.0

I might take a look into this soonish if nobody else does.

**Closed as completed** 2018-12-29 16:10 UTC

**Comment by vweevers** [comment] 2020-01-23 15:27
Finally figured this out for real!

For Android and iOS, we and Sauce Labs use the appium automation backend. However, [`sauce-browsers`](https://github.com/lpinca/sauce-browsers) fetches `/rest/v1/info/platforms/webdriver` rather than `/rest/v1/info/platforms/all`. The latter also includes appium-only browsers, including the one we need for android 7+: "Android GoogleAPI Emulator" (which is hardcoded in airtap atm).

**Comment by vweevers** [comment] 2020-01-23 15:32
Plus, we should be sending it to Sauce Labs like so:

```js
caps['deviceName'] = 'Android GoogleAPI Emulator';
caps['browserName'] = 'Chrome';
caps['platformVersion'] = '7.1';
caps['platformName'] = 'Android';
```

Rather than what we do now (which Sauce Labs in fact translates into the above):

```js
caps['deviceName'] = 'Android GoogleAPI Emulator';
caps['browserName'] = 'android';
caps['version'] = '7.1';
caps['platform'] = 'Linux';
```

**Comment by vweevers** [comment] 2020-01-25 13:14
Wrote https://github.com/airtap/sauce-browsers to handle this (will replace `sauce-browsers`).
